version: 2


defaults: &defaults # reusable block that we can insert elsewhere
  docker:
    - image: jcolemorrison/circleci-node-awscli:latest
  working_directory: ~/project # the working directory of the CI steps and job

# where we define "jobs" aka, things to be done
# these are NOT ordered.  We simply define them here.
jobs:
  install: # first key is the name of the job
    <<: *defaults # resuse defaults block information

    steps: # define the STEPS that we want to take
      - checkout # CircleCI helper - checks out the codebase
      - restore_cache: # restore cached node modules if we have any
          keys:
            - node-modules-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run: # run the yarn install command
          name: Install
          command: yarn install
      - save_cache:
          paths:
            - node_modules
          key: node_modules-{{ .Branch }}-{{ checksum "yarn.lock" }}

      # save what we did in this step and make it available to the next job
      # by default, what you do doesn't persist, so we have to make it persist
      # so we just persist our entire current directory in the CI which is:
      # ~/project
      - persist_to_workspace:
          root: .
          paths:
            - .

  test:
    <<: *defaults
    steps:
      - attach_workspace: # attach what you did in previous job in this job
          at: .
      - run:
          name: Test
          command: yarn test

  deploy:
    <<: *defaults
    steps:
      - attach_workspace: # attach what you did in previous job in this job
          at: .
      - setup_remote_docker  # necessary to hook into docker
      - run:
          name: Set ENV Variables
          # $BASH_ENV is what you add values to that you want made available in this particular job
          command: |
            echo 'export IMAGE=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/lowdevops/api' >> $BASH_ENV
      - run: # run the build script
          name: build image and deploy
          command: |
            chmod +x ./deploy.sh
            ./deploy.sh

# Where we define the actual order of jobs
workflows:
  version: 2

  # other than version, the top level is the NAME of workflows
  install_test_deploy:
    # other keys here
    # jobs is how we ORDER the above jobs, define what they require, and create conditions
    # but we order them via `requires`, not just the array order
    # by default without `requires` statement CircleCI attempts to run all jobs in parallel -- NO-NO!!!
    # etc:
    # you can run multiple jobs in parallel (add fake step and requires install)
    # `requires` can require the completion of multiple steps
    jobs:
      - install
      - test:
          requires:
            - install
      - deploy:
          requires:
            - test
          filters:
            # mention that this is how you'd filter for
            # production and staging
            branches:
              only:
                - staging
